"""Added unique constraint meter_id for monthlyenergy

Revision ID: 46b1c3685235
Revises: 92bea9ad84bf
Create Date: 2026-03-03 10:31:23.040779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46b1c3685235"
down_revision: Union[str, Sequence[str], None] = "92bea9ad84bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("monthlyenergy") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.create_unique_constraint(
            "uq_monthlyenergy_year_month_day_meter",
            ["year", "month", "day", "meter_id"],
        )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("monthlyenergy") as batch_op:
        batch_op.drop_constraint(
            "uq_monthlyenergy_year_month_day_meter", type_="unique"
        )
