"""initial migration

Revision ID: 92bea9ad84bf
Revises: 
Create Date: 2026-03-03 10:07:35.398047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bea9ad84bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlyenergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('total_energy', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'day')
    )
    op.create_index(op.f('ix_monthlyenergy_day'), 'monthlyenergy', ['day'], unique=False)
    op.create_index(op.f('ix_monthlyenergy_meter_id'), 'monthlyenergy', ['meter_id'], unique=False)
    op.create_index(op.f('ix_monthlyenergy_month'), 'monthlyenergy', ['month'], unique=False)
    op.create_index(op.f('ix_monthlyenergy_year'), 'monthlyenergy', ['year'], unique=False)
    op.create_table('weeksenergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('total_energy', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'week', 'meter_id')
    )
    op.create_index(op.f('ix_weeksenergy_meter_id'), 'weeksenergy', ['meter_id'], unique=False)
    op.create_index(op.f('ix_weeksenergy_week'), 'weeksenergy', ['week'], unique=False)
    op.create_index(op.f('ix_weeksenergy_year'), 'weeksenergy', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeksenergy_year'), table_name='weeksenergy')
    op.drop_index(op.f('ix_weeksenergy_week'), table_name='weeksenergy')
    op.drop_index(op.f('ix_weeksenergy_meter_id'), table_name='weeksenergy')
    op.drop_table('weeksenergy')
    op.drop_index(op.f('ix_monthlyenergy_year'), table_name='monthlyenergy')
    op.drop_index(op.f('ix_monthlyenergy_month'), table_name='monthlyenergy')
    op.drop_index(op.f('ix_monthlyenergy_meter_id'), table_name='monthlyenergy')
    op.drop_index(op.f('ix_monthlyenergy_day'), table_name='monthlyenergy')
    op.drop_table('monthlyenergy')
    # ### end Alembic commands ###
